CREATE TABLE ASSINANTE (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100)
);

CREATE TABLE RECEITA (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    DESCRICAO VARCHAR(100)
);